// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs-pchQRxJ6SHMHSs1XmRaw7MwOiiaY_k',
    appId: '1:432970570650:web:5a548c95395fde3c073823',
    messagingSenderId: '432970570650',
    projectId: 'sirius-hub-df66a',
    authDomain: 'sirius-hub-df66a.firebaseapp.com',
    storageBucket: 'sirius-hub-df66a.firebasestorage.app',
    measurementId: 'G-WJ1VSSF7RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxvLKNVHwXsf-nnOa3nYgMoLEl9VA0t9k',
    appId: '1:432970570650:android:18a0efc017730ca2073823',
    messagingSenderId: '432970570650',
    projectId: 'sirius-hub-df66a',
    storageBucket: 'sirius-hub-df66a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ_OSzFbSrDaSAQt8qmCdIB3gi-NnF9Fg',
    appId: '1:432970570650:ios:3a8ea345eded0d9e073823',
    messagingSenderId: '432970570650',
    projectId: 'sirius-hub-df66a',
    storageBucket: 'sirius-hub-df66a.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ_OSzFbSrDaSAQt8qmCdIB3gi-NnF9Fg',
    appId: '1:432970570650:ios:3a8ea345eded0d9e073823',
    messagingSenderId: '432970570650',
    projectId: 'sirius-hub-df66a',
    storageBucket: 'sirius-hub-df66a.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs-pchQRxJ6SHMHSs1XmRaw7MwOiiaY_k',
    appId: '1:432970570650:web:daa4a68081d98c91073823',
    messagingSenderId: '432970570650',
    projectId: 'sirius-hub-df66a',
    authDomain: 'sirius-hub-df66a.firebaseapp.com',
    storageBucket: 'sirius-hub-df66a.firebasestorage.app',
    measurementId: 'G-GX7TQKZEMN',
  );
}
