// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAgK8N_SfkE6BxyNdZzkQllA-gAdRnJ0k',
    appId: '1:265696164054:web:2123184be6fa5495357177',
    messagingSenderId: '265696164054',
    projectId: 'camphub-sirius-ee21d',
    authDomain: 'camphub-sirius-ee21d.firebaseapp.com',
    storageBucket: 'camphub-sirius-ee21d.firebasestorage.app',
    measurementId: 'G-CH9VWJSQFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jIqzURVVRU6naC-G370MRVQEzl1ikX4',
    appId: '1:265696164054:android:a2ffc70b333f5980357177',
    messagingSenderId: '265696164054',
    projectId: 'camphub-sirius-ee21d',
    storageBucket: 'camphub-sirius-ee21d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB59sv3kSO7S_tr2ZrH0K4MbSiKenjdt8',
    appId: '1:265696164054:ios:83803eac98e2eec7357177',
    messagingSenderId: '265696164054',
    projectId: 'camphub-sirius-ee21d',
    storageBucket: 'camphub-sirius-ee21d.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB59sv3kSO7S_tr2ZrH0K4MbSiKenjdt8',
    appId: '1:265696164054:ios:83803eac98e2eec7357177',
    messagingSenderId: '265696164054',
    projectId: 'camphub-sirius-ee21d',
    storageBucket: 'camphub-sirius-ee21d.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAgK8N_SfkE6BxyNdZzkQllA-gAdRnJ0k',
    appId: '1:265696164054:web:aa523de9d50f15e9357177',
    messagingSenderId: '265696164054',
    projectId: 'camphub-sirius-ee21d',
    authDomain: 'camphub-sirius-ee21d.firebaseapp.com',
    storageBucket: 'camphub-sirius-ee21d.firebasestorage.app',
    measurementId: 'G-X4G7PTYY30',
  );
}
