"""fields for news

Revision ID: 12cb95a95dda
Revises: a1cdfa8b0b3a
Create Date: 2026-07-18 17:10:49.221562

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12cb95a95dda"
down_revision: Union[str, Sequence[str], None] = "a1cdfa8b0b3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offerevent",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_status", sa.String(), nullable=True),
        sa.Column("news_id", sa.String(), nullable=False),
        sa.Column("event_start", sa.String(), nullable=False),
        sa.Column("event_end", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("max_partic", sa.Integer(), nullable=False),
        sa.Column("cur_partic", sa.Integer(), nullable=False),
        sa.Column("is_reg_open", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("offerevent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offerevent_id"), ["id"], unique=False)

    op.create_table(
        "offernews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("contacts_author", sa.String(), nullable=False),
        sa.Column("has_event", sa.Boolean(), nullable=True),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("has_topic", sa.Boolean(), nullable=True),
        sa.Column("topic_id", sa.String(), nullable=True),
        sa.Column("status_mod", sa.String(), nullable=True),
        sa.Column("admin_id", sa.String(), nullable=True),
        sa.Column("comment_admin", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("offernews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offernews_id"), ["id"], unique=False)

    op.create_table(
        "offertopics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("anon", sa.Boolean(), nullable=False),
        sa.Column("news_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("offertopics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offertopics_id"), ["id"], unique=False)

    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.add_column(sa.Column("has_event", sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column("has_topic", sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column("topic_id", sa.String(), nullable=True))
        batch_op.drop_column("is_event")

    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("news_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_column("news_id")

    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_event", sa.BOOLEAN(), nullable=False))
        batch_op.drop_column("topic_id")
        batch_op.drop_column("has_topic")
        batch_op.drop_column("has_event")

    with op.batch_alter_table("offertopics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offertopics_id"))

    op.drop_table("offertopics")
    with op.batch_alter_table("offernews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offernews_id"))

    op.drop_table("offernews")
    with op.batch_alter_table("offerevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offerevent_id"))

    op.drop_table("offerevent")
    # ### end Alembic commands ###
