"""add study_groups

Revision ID: 5a1e237bc965
Revises: b847309934aa
Create Date: 2026-10-04 16:30:03.489763

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a1e237bc965"
down_revision: Union[str, Sequence[str], None] = "adcc11507ec0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_groups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("study_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_study_groups_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_groups_id"))

    op.drop_table("study_groups")
    # ### end Alembic commands ###
