"""renamed tg_header

Revision ID: 66c5a45d86d0
Revises: 12cb95a95dda
Create Date: 2026-09-16 20:37:40.775779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c5a45d86d0'
down_revision: Union[str, Sequence[str], None] = '12cb95a95dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('is_event')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messenger_handle', sa.String(length=33), nullable=True))
        batch_op.drop_column('telegram_handle')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_handle', sa.VARCHAR(length=33), nullable=True))
        batch_op.drop_column('messenger_handle')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_event', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
