"""new

Revision ID: 81a528019d8c
Revises: b847309934aa
Create Date: 2026-09-22 13:59:02.192552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a528019d8c'
down_revision: Union[str, Sequence[str], None] = 'b847309934aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1024),
               existing_nullable=False)

    with op.batch_alter_table('offertopics', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=False)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=60),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messenger_handle', sa.String(length=32), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=70),
               existing_nullable=True)
        batch_op.drop_column('telegram_handle')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_handle', sa.VARCHAR(length=33), nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('messenger_handle')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('offertopics', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
