"""initial init

Revision ID: 881bb7adf357
Revises:
Create Date: 2026-07-15 12:58:34.440649

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "881bb7adf357"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_event", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("event_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.drop_column("event_id")
        batch_op.drop_column("is_event")

    # ### end Alembic commands ###
