"""added new fields

Revision ID: a1cdfa8b0b3a
Revises: 881bb7adf357
Create Date: 2026-07-17 18:45:10.022607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cdfa8b0b3a'
down_revision: Union[str, Sequence[str], None] = '881bb7adf357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_id'))

    op.drop_table('offers')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_comment_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('parent_comment_id')

    op.create_table('offers',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('author_id', sa.VARCHAR(), nullable=False),
    sa.Column('contacts_author', sa.VARCHAR(), nullable=False),
    sa.Column('is_event', sa.BOOLEAN(), nullable=True),
    sa.Column('event_id', sa.VARCHAR(), nullable=True),
    sa.Column('status_mod', sa.VARCHAR(), nullable=True),
    sa.Column('admin_id', sa.VARCHAR(), nullable=True),
    sa.Column('comment_admin', sa.TEXT(), nullable=True),
    sa.Column('moderated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('event_status', sa.VARCHAR(), nullable=True),
    sa.Column('event_start', sa.VARCHAR(), nullable=False),
    sa.Column('event_end', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('max_partic', sa.INTEGER(), nullable=False),
    sa.Column('cur_partic', sa.INTEGER(), nullable=False),
    sa.Column('is_reg_open', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_id'), ['id'], unique=False)

    # ### end Alembic commands ###
