"""Add foreign_keys

Revision ID: afb11306522c
Revises: 81a528019d8c
Create Date: 2026-09-30 19:52:05.678977

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afb11306522c"
down_revision: Union[str, Sequence[str], None] = "81a528019d8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_comments_user_id_users", "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_comments_parent_comment_id_comments",
            "comments",
            ["parent_comment_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
