"""Initial full migration

Revision ID: b847309934aa
Revises:
Create Date: 2026-09-17 18:54:59.831101

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b847309934aa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("topic_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("content", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("parent_comment_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_comments_topic_id"), ["topic_id"], unique=False
        )

    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("news_id", sa.String(), nullable=False),
        sa.Column("event_start", sa.String(), nullable=False),
        sa.Column("event_end", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("max_partic", sa.Integer(), nullable=False),
        sa.Column("cur_partic", sa.Integer(), nullable=False),
        sa.Column("is_reg_open", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_id"), ["id"], unique=False)

    op.create_table(
        "news",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("has_event", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("has_topic", sa.Boolean(), nullable=False),
        sa.Column("topic_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_news_id"), ["id"], unique=False)

    op.create_table(
        "offerevent",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_status", sa.String(), nullable=True),
        sa.Column("news_id", sa.String(), nullable=False),
        sa.Column("event_start", sa.String(), nullable=False),
        sa.Column("event_end", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("max_partic", sa.Integer(), nullable=False),
        sa.Column("cur_partic", sa.Integer(), nullable=False),
        sa.Column("is_reg_open", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("offerevent", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offerevent_id"), ["id"], unique=False)

    op.create_table(
        "offernews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("contacts_author", sa.String(), nullable=False),
        sa.Column("has_event", sa.Boolean(), nullable=True),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("has_topic", sa.Boolean(), nullable=True),
        sa.Column("topic_id", sa.String(), nullable=True),
        sa.Column("status_mod", sa.String(), nullable=True),
        sa.Column("admin_id", sa.String(), nullable=True),
        sa.Column("comment_admin", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("offernews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offernews_id"), ["id"], unique=False)

    op.create_table(
        "offertopics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("anon", sa.Boolean(), nullable=False),
        sa.Column("news_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("offertopics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_offertopics_id"), ["id"], unique=False)

    op.create_table(
        "registrations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("comment", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("registrations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_registrations_id"), ["id"], unique=False)

    op.create_table(
        "topics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("anon", sa.Boolean(), nullable=False),
        sa.Column("news_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topics_id"), ["id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("avatar_emoji", sa.String(length=16), nullable=True),
        sa.Column("display_name", sa.String(length=30), nullable=True),
        sa.Column("group_code", sa.String(length=20), nullable=True),
        sa.Column("bio", sa.String(length=200), nullable=True),
        sa.Column("telegram_handle", sa.String(length=33), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topics_id"))

    op.drop_table("topics")
    with op.batch_alter_table("registrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_registrations_id"))

    op.drop_table("registrations")
    with op.batch_alter_table("offertopics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offertopics_id"))

    op.drop_table("offertopics")
    with op.batch_alter_table("offernews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offernews_id"))

    op.drop_table("offernews")
    with op.batch_alter_table("offerevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_offerevent_id"))

    op.drop_table("offerevent")
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_id"))

    op.drop_table("news")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_id"))

    op.drop_table("events")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_topic_id"))
        batch_op.drop_index(batch_op.f("ix_comments_id"))

    op.drop_table("comments")
    # ### end Alembic commands ###
