
USER_AVATAR_EMOJI_MAX_LEN = 16
USER_DISPLAY_NAME_MAX_LEN = 30
USER_BIO_MAX_LEN = 70
USER_MESSENGER_HANDLE_MAX_LEN = 32
USER_MESSENGER_HANDLE_MIN_LEN = 5
USER_GROUP_CODE_MAX_LEN = 20
USER_COMMENT_MAX_LEN = 1024 #комментарий
USER_EMAIL_LEN = 254

COMMENT_MAX = 50 #к заявке
TITLE_LEN = 60
CONTENT_LEN = 4096
MIN_LEN = 1


EVENT_LOCATION_LEN = 70