name: Deploy FastAPI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            mkdir -p ~/app/Sirius-hub
            cd ~/app/Sirius-hub

            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            fi

            git fetch origin
            git checkout main
            git reset --hard origin/main

            cd backend

            touch .env

            sed -i '/FIREBASE_CONFIG_BASE64/d' .env

            echo "FIREBASE_CONFIG_BASE64='${{ secrets.FIREBASE_CONFIG_BASE64 }}'" > .env
            echo "DB_USER='${{ secrets.DB_USER }}'" >> .env
            echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> .env
            echo "DB_NAME='${{ secrets.DB_NAME }}'" >> .env

            docker compose down
            docker compose up -d --build
            docker exec camphub-fastapi python -m alembic upgrade head